---
# tasks file for builder
- name: Ensure package is present
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - git
    - default-jdk
    - maven
- name: create directory
  file: path=/home/boxfuse state=directory
- name: clone repository
  git: repo=https://github.com/boxfuse/boxfuse-sample-java-war-hello.git dest=/home/boxfuse
- name: build package
  shell: mvn package
  args:
    chdir: /home/boxfuse
- name: Get file from build
  fetch:
    src: /home/boxfuse/target/hello-1.0.war
    dest: hello-1.0.war
    flat: yes