- name: build boxfuse
  hosts: build
  remote_user: ubuntu
  become: yes
  become_user: root

  tasks:
    - name: Ensure package is present
      apt: name={{item}} state=present
      with_items:
        - git
        - default-jdk
        - maven
    - name: create directory
      file: path=/home/boxfuse state=directory
    - name: clone repository
      git: repo=https://github.com/boxfuse/boxfuse-sample-java-war-hello.git dest=/home/boxfuse
    - name: build package
      shell: mvn package
      args:
        chdir: /home/boxfuse
    - name: Create a data container
      docker_container:
        name: tomcat_cont
        image: tomcat:alpine
    - name: Copy build to container
      shell: docker cp /home/boxfuse/target/hello-1.0.war tomcat_cont:/usr/local/tomcat/webapps/hello-1.0.war
    - name: PUT build to bucket
      aws_s3:
        bucket: project.dmitrydok.com
        object: hello-1.0.war
        src: /home/boxfuse/target/hello-1.0.war
        mode: put