- name: build boxfuse
  hosts: builder
  remote_user: ubuntu
  become: yes
  become_user: root

  tasks:
    - name: Ensure package is present
      apt: name={{item}} state=present
      with_items:
        - git
        - default-jdk
        - maven
    - name: create directory
      file: path=/home/boxfuse state=directory
    - name: clone repository
      git: repo=https://github.com/boxfuse/boxfuse-sample-java-war-hello.git dest=/home/boxfuse
    - name: build package
      shell: mvn package
      args:
        chdir: /home/boxfuse
    - name: PUT build to bucket
      aws_s3:
        bucket: mybacket1.dmitry-test.com
        object: hello-1.0.war
        src: /home/boxfuse/target/hello-1.0.war
        mode: put