---
- name: builder
  hosts: build
  remote_user: ubuntu
  become: yes
  become_user: root
  roles:
    - builder

- name: prodakshen build
  hosts: prod
  remote_user: ubuntu
  become: yes
  become_user: root
  roles:
    - prod
