---
# tasks file for prod
- name: Ensure package is present
  apt: name=docker.io state=present update_cache=yes
- name: create directory
  file: path=/home/boxfuse state=directory
- name: Send file to prod
  copy:
    src: hello-1.0.war
    dest: /home/boxfuse
    follow: yes
- name: Create a data container
  docker_container:
    name: prodtomcat
    image: tomcat:alpine
    volumes:
      - "/home/boxfuse:/usr/local/tomcat/webapps"
    ports:
      - "8080:8080"